name: Releasing v0_$(Date:yyyyMMdd)$(Rev:.r)

on:
  push:
    branches:
      - master

jobs:
  release:
    name: 'Publish ðŸš€'
    runs-on: ubuntu-latest
    steps:
      - name: Publishing âœ¨
        uses: ./
        with:
            run: yarn publish:beachball -n ${{secrets.NPM_TOKEN}}
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
